name: fss_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  retrofit: ^4.0.1
  meta: ^1.9.1
  json_annotation: ^4.8.1
  get_cli: ^1.8.4
  logger: ^2.0.1
  dio: ^5.3.2
  connectivity_plus: ^4.0.2
  nb_utils: ^6.0.2
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  flutter_form_builder: ^9.1.0
  get: 4.6.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.2
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter

scripts:
  gen: flutter pub run build_runner watch --delete-conflicting-outputs
  format: get sort ./lib

get_cli:
  separator: .
  sub_folder: false

flutter:
  uses-material-design: true
